apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-test2
spec:
  replicas: 1
  selector:
    name: nfs-test2
  template:
    metadata:
      labels:
        name: nfs-test2
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do sleep $(($RANDOM % 5 + 5)); ls -lah /mnt/;  done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: test-bucket-nfs2-server-claim
            mountPath: "/mnt"
      volumes:
      - name: test-bucket-nfs2-server-claim
        persistentVolumeClaim:
          claimName: test-bucket-nfs2-server-claim