apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${nfsBucketServerName}-bucket
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${nfsBucketServerName}.default.svc.cluster.local
    path: "/"